// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: gophkeeper.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RegisterRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Login          string                 `protobuf:"bytes,1,opt,name=login,proto3" json:"login,omitempty"`
	Password       string                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	MasterPassword string                 `protobuf:"bytes,3,opt,name=master_password,json=masterPassword,proto3" json:"master_password,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *RegisterRequest) Reset() {
	*x = RegisterRequest{}
	mi := &file_gophkeeper_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterRequest) ProtoMessage() {}

func (x *RegisterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_gophkeeper_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterRequest.ProtoReflect.Descriptor instead.
func (*RegisterRequest) Descriptor() ([]byte, []int) {
	return file_gophkeeper_proto_rawDescGZIP(), []int{0}
}

func (x *RegisterRequest) GetLogin() string {
	if x != nil {
		return x.Login
	}
	return ""
}

func (x *RegisterRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *RegisterRequest) GetMasterPassword() string {
	if x != nil {
		return x.MasterPassword
	}
	return ""
}

type LoginRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Login          string                 `protobuf:"bytes,1,opt,name=login,proto3" json:"login,omitempty"`
	Password       string                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	MasterPassword string                 `protobuf:"bytes,3,opt,name=master_password,json=masterPassword,proto3" json:"master_password,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *LoginRequest) Reset() {
	*x = LoginRequest{}
	mi := &file_gophkeeper_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginRequest) ProtoMessage() {}

func (x *LoginRequest) ProtoReflect() protoreflect.Message {
	mi := &file_gophkeeper_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginRequest.ProtoReflect.Descriptor instead.
func (*LoginRequest) Descriptor() ([]byte, []int) {
	return file_gophkeeper_proto_rawDescGZIP(), []int{1}
}

func (x *LoginRequest) GetLogin() string {
	if x != nil {
		return x.Login
	}
	return ""
}

func (x *LoginRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *LoginRequest) GetMasterPassword() string {
	if x != nil {
		return x.MasterPassword
	}
	return ""
}

type TokenResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Token         string                 `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TokenResponse) Reset() {
	*x = TokenResponse{}
	mi := &file_gophkeeper_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TokenResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TokenResponse) ProtoMessage() {}

func (x *TokenResponse) ProtoReflect() protoreflect.Message {
	mi := &file_gophkeeper_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TokenResponse.ProtoReflect.Descriptor instead.
func (*TokenResponse) Descriptor() ([]byte, []int) {
	return file_gophkeeper_proto_rawDescGZIP(), []int{2}
}

func (x *TokenResponse) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

type UpsertRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DataKey       string                 `protobuf:"bytes,1,opt,name=data_key,json=dataKey,proto3" json:"data_key,omitempty"`
	DataValue     []byte                 `protobuf:"bytes,2,opt,name=data_value,json=dataValue,proto3" json:"data_value,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	DeletedAt     *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=deleted_at,json=deletedAt,proto3" json:"deleted_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpsertRequest) Reset() {
	*x = UpsertRequest{}
	mi := &file_gophkeeper_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpsertRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpsertRequest) ProtoMessage() {}

func (x *UpsertRequest) ProtoReflect() protoreflect.Message {
	mi := &file_gophkeeper_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpsertRequest.ProtoReflect.Descriptor instead.
func (*UpsertRequest) Descriptor() ([]byte, []int) {
	return file_gophkeeper_proto_rawDescGZIP(), []int{3}
}

func (x *UpsertRequest) GetDataKey() string {
	if x != nil {
		return x.DataKey
	}
	return ""
}

func (x *UpsertRequest) GetDataValue() []byte {
	if x != nil {
		return x.DataValue
	}
	return nil
}

func (x *UpsertRequest) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

func (x *UpsertRequest) GetDeletedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.DeletedAt
	}
	return nil
}

type GetUpdatesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UpdatedAfter  *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=updated_after,json=updatedAfter,proto3" json:"updated_after,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUpdatesRequest) Reset() {
	*x = GetUpdatesRequest{}
	mi := &file_gophkeeper_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUpdatesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUpdatesRequest) ProtoMessage() {}

func (x *GetUpdatesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_gophkeeper_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUpdatesRequest.ProtoReflect.Descriptor instead.
func (*GetUpdatesRequest) Descriptor() ([]byte, []int) {
	return file_gophkeeper_proto_rawDescGZIP(), []int{4}
}

func (x *GetUpdatesRequest) GetUpdatedAfter() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAfter
	}
	return nil
}

type DataResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DataKey       string                 `protobuf:"bytes,1,opt,name=data_key,json=dataKey,proto3" json:"data_key,omitempty"`
	DataValue     []byte                 `protobuf:"bytes,2,opt,name=data_value,json=dataValue,proto3" json:"data_value,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	DeletedAt     *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=deleted_at,json=deletedAt,proto3" json:"deleted_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DataResponse) Reset() {
	*x = DataResponse{}
	mi := &file_gophkeeper_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DataResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DataResponse) ProtoMessage() {}

func (x *DataResponse) ProtoReflect() protoreflect.Message {
	mi := &file_gophkeeper_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DataResponse.ProtoReflect.Descriptor instead.
func (*DataResponse) Descriptor() ([]byte, []int) {
	return file_gophkeeper_proto_rawDescGZIP(), []int{5}
}

func (x *DataResponse) GetDataKey() string {
	if x != nil {
		return x.DataKey
	}
	return ""
}

func (x *DataResponse) GetDataValue() []byte {
	if x != nil {
		return x.DataValue
	}
	return nil
}

func (x *DataResponse) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

func (x *DataResponse) GetDeletedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.DeletedAt
	}
	return nil
}

type DataListResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*DataResponse        `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DataListResponse) Reset() {
	*x = DataListResponse{}
	mi := &file_gophkeeper_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DataListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DataListResponse) ProtoMessage() {}

func (x *DataListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_gophkeeper_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DataListResponse.ProtoReflect.Descriptor instead.
func (*DataListResponse) Descriptor() ([]byte, []int) {
	return file_gophkeeper_proto_rawDescGZIP(), []int{6}
}

func (x *DataListResponse) GetItems() []*DataResponse {
	if x != nil {
		return x.Items
	}
	return nil
}

var File_gophkeeper_proto protoreflect.FileDescriptor

const file_gophkeeper_proto_rawDesc = "" +
	"\n" +
	"\x10gophkeeper.proto\x12\rgophkeeper.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"l\n" +
	"\x0fRegisterRequest\x12\x14\n" +
	"\x05login\x18\x01 \x01(\tR\x05login\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\x12'\n" +
	"\x0fmaster_password\x18\x03 \x01(\tR\x0emasterPassword\"i\n" +
	"\fLoginRequest\x12\x14\n" +
	"\x05login\x18\x01 \x01(\tR\x05login\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\x12'\n" +
	"\x0fmaster_password\x18\x03 \x01(\tR\x0emasterPassword\"%\n" +
	"\rTokenResponse\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token\"\xbf\x01\n" +
	"\rUpsertRequest\x12\x19\n" +
	"\bdata_key\x18\x01 \x01(\tR\adataKey\x12\x1d\n" +
	"\n" +
	"data_value\x18\x02 \x01(\fR\tdataValue\x129\n" +
	"\n" +
	"updated_at\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\x129\n" +
	"\n" +
	"deleted_at\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\tdeletedAt\"T\n" +
	"\x11GetUpdatesRequest\x12?\n" +
	"\rupdated_after\x18\x01 \x01(\v2\x1a.google.protobuf.TimestampR\fupdatedAfter\"\xbe\x01\n" +
	"\fDataResponse\x12\x19\n" +
	"\bdata_key\x18\x01 \x01(\tR\adataKey\x12\x1d\n" +
	"\n" +
	"data_value\x18\x02 \x01(\fR\tdataValue\x129\n" +
	"\n" +
	"updated_at\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\x129\n" +
	"\n" +
	"deleted_at\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\tdeletedAt\"E\n" +
	"\x10DataListResponse\x121\n" +
	"\x05items\x18\x01 \x03(\v2\x1b.gophkeeper.v1.DataResponseR\x05items2\x9b\x01\n" +
	"\vAuthService\x12H\n" +
	"\bRegister\x12\x1e.gophkeeper.v1.RegisterRequest\x1a\x1c.gophkeeper.v1.TokenResponse\x12B\n" +
	"\x05Login\x12\x1b.gophkeeper.v1.LoginRequest\x1a\x1c.gophkeeper.v1.TokenResponse2\xa3\x01\n" +
	"\vDataService\x12C\n" +
	"\x06Upsert\x12\x1c.gophkeeper.v1.UpsertRequest\x1a\x1b.gophkeeper.v1.DataResponse\x12O\n" +
	"\n" +
	"GetUpdates\x12 .gophkeeper.v1.GetUpdatesRequest\x1a\x1f.gophkeeper.v1.DataListResponseB6Z4github.com/m1khal3v/gophkeeper/internal/common/protob\x06proto3"

var (
	file_gophkeeper_proto_rawDescOnce sync.Once
	file_gophkeeper_proto_rawDescData []byte
)

func file_gophkeeper_proto_rawDescGZIP() []byte {
	file_gophkeeper_proto_rawDescOnce.Do(func() {
		file_gophkeeper_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_gophkeeper_proto_rawDesc), len(file_gophkeeper_proto_rawDesc)))
	})
	return file_gophkeeper_proto_rawDescData
}

var file_gophkeeper_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_gophkeeper_proto_goTypes = []any{
	(*RegisterRequest)(nil),       // 0: gophkeeper.v1.RegisterRequest
	(*LoginRequest)(nil),          // 1: gophkeeper.v1.LoginRequest
	(*TokenResponse)(nil),         // 2: gophkeeper.v1.TokenResponse
	(*UpsertRequest)(nil),         // 3: gophkeeper.v1.UpsertRequest
	(*GetUpdatesRequest)(nil),     // 4: gophkeeper.v1.GetUpdatesRequest
	(*DataResponse)(nil),          // 5: gophkeeper.v1.DataResponse
	(*DataListResponse)(nil),      // 6: gophkeeper.v1.DataListResponse
	(*timestamppb.Timestamp)(nil), // 7: google.protobuf.Timestamp
}
var file_gophkeeper_proto_depIdxs = []int32{
	7,  // 0: gophkeeper.v1.UpsertRequest.updated_at:type_name -> google.protobuf.Timestamp
	7,  // 1: gophkeeper.v1.UpsertRequest.deleted_at:type_name -> google.protobuf.Timestamp
	7,  // 2: gophkeeper.v1.GetUpdatesRequest.updated_after:type_name -> google.protobuf.Timestamp
	7,  // 3: gophkeeper.v1.DataResponse.updated_at:type_name -> google.protobuf.Timestamp
	7,  // 4: gophkeeper.v1.DataResponse.deleted_at:type_name -> google.protobuf.Timestamp
	5,  // 5: gophkeeper.v1.DataListResponse.items:type_name -> gophkeeper.v1.DataResponse
	0,  // 6: gophkeeper.v1.AuthService.Register:input_type -> gophkeeper.v1.RegisterRequest
	1,  // 7: gophkeeper.v1.AuthService.Login:input_type -> gophkeeper.v1.LoginRequest
	3,  // 8: gophkeeper.v1.DataService.Upsert:input_type -> gophkeeper.v1.UpsertRequest
	4,  // 9: gophkeeper.v1.DataService.GetUpdates:input_type -> gophkeeper.v1.GetUpdatesRequest
	2,  // 10: gophkeeper.v1.AuthService.Register:output_type -> gophkeeper.v1.TokenResponse
	2,  // 11: gophkeeper.v1.AuthService.Login:output_type -> gophkeeper.v1.TokenResponse
	5,  // 12: gophkeeper.v1.DataService.Upsert:output_type -> gophkeeper.v1.DataResponse
	6,  // 13: gophkeeper.v1.DataService.GetUpdates:output_type -> gophkeeper.v1.DataListResponse
	10, // [10:14] is the sub-list for method output_type
	6,  // [6:10] is the sub-list for method input_type
	6,  // [6:6] is the sub-list for extension type_name
	6,  // [6:6] is the sub-list for extension extendee
	0,  // [0:6] is the sub-list for field type_name
}

func init() { file_gophkeeper_proto_init() }
func file_gophkeeper_proto_init() {
	if File_gophkeeper_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_gophkeeper_proto_rawDesc), len(file_gophkeeper_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_gophkeeper_proto_goTypes,
		DependencyIndexes: file_gophkeeper_proto_depIdxs,
		MessageInfos:      file_gophkeeper_proto_msgTypes,
	}.Build()
	File_gophkeeper_proto = out.File
	file_gophkeeper_proto_goTypes = nil
	file_gophkeeper_proto_depIdxs = nil
}
