name: gophkeeper-release

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build
        uses: crazy-max/ghaction-xgo@v3
        with:
          go_version: 1.24
          prefix: client
          targets: windows/amd64, linux/amd64, linux/arm64, darwin/arm64
          v: true
          pkg: cmd/client
          
      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            build/client-linux-amd64
            build/client-linux-arm64
            build/client-win-amd64.exe
            build/client-darwin-arm64
