name: gophkeeper-release

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  release:
    runs-on: ubuntu-latest
    container: golang:1.24
    strategy:
      matrix:
        goos: [linux, windows, darwin]
        goarch: [amd64, arm64]

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build linux-amd64
        run: |
          CGO_ENABLED=1 GOOS=linux GOARCH=amd64 go build -C ./cmd/client -buildvcs=false -o client-linux-amd64

      - name: Build windows-amd64
        run: |
          CGO_ENABLED=1 GOOS=windows GOARCH=amd64 go build -C ./cmd/client -buildvcs=false -o client-win-amd64.exe

      - name: Build macos-amd64
        run: |
          CGO_ENABLED=1 GOOS=darwin GOARCH=amd64 go build -C ./cmd/client -buildvcs=false -o client-macos-amd64
          
      - name: Build linux-arm64
        run: |
          CGO_ENABLED=1 GOOS=linux GOARCH=arm64 go build -C ./cmd/client -buildvcs=false -o client-linux-arm64

      - name: Build windows-arm64
        run: |
          CGO_ENABLED=1 GOOS=windows GOARCH=arm64 go build -C ./cmd/client -buildvcs=false -o client-win-arm64.exe

      - name: Build macos-arm64
        run: |
          CGO_ENABLED=1 GOOS=darwin GOARCH=arm64 go build -C ./cmd/client -buildvcs=false -o client-macos-arm64
          
      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            client-linux-amd64
            client-win-amd64.exe
            client-macos-amd64
            client-linux-arm64
            client-win-arm64.exe
            client-macos-arm64
